CREATE INDEX CONCURRENTLY IF NOT EXISTS DATA_TYPE_STRING_EQ ON DATA(TYPE_NAME, STRING);
CREATE INDEX CONCURRENTLY IF NOT EXISTS DATA_TYPE_NUMBER ON DATA(TYPE_NAME, NUM);
CREATE INDEX CONCURRENTLY IF NOT EXISTS DATA_TYPE_ITEM ON DATA(TYPE_NAME, ITEM_ID);
CREATE INDEX CONCURRENTLY IF NOT EXISTS DATA_TYPE_LCSTRING_EQ ON DATA(TYPE_NAME, (LOWER(STRING)));
CREATE INDEX CONCURRENTLY IF NOT EXISTS DATA_OWNER ON DATA(OWNER_ID);
CREATE INDEX CONCURRENTLY IF NOT EXISTS DATA_ROOT ON DATA(ROOT_ID);
