CREATE INDEX CONCURRENTLY IF NOT EXISTS ITEM_TYPE_PARENT ON ITEM(PARENT_ID, TYPE_NAME);
CREATE INDEX CONCURRENTLY IF NOT EXISTS ITEM_ROOT ON ITEM(ROOT_ID);
CREATE INDEX CONCURRENTLY IF NOT EXISTS ITEM_PATH ON ITEM(PATH VARCHAR_PATTERN_OPS);
CREATE INDEX CONCURRENTLY IF NOT EXISTS ITEM_DELETED_NZ ON ITEM(DELETED) WHERE DELETED IS NOT NULL;
