/*
 * LO Platform copyright (C) 2007–2025 LO Ventures LLC.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//data updates

export const DISCUSSION_UPDATE_LAST_VISITED = 'DISCUSSION_UPDATE_LAST_VISITED';
export const DISCUSSION_VISITED_NOTICE = 'DISCUSSION_VISITED_NOTICE';
export const DISCUSSION_UPDATE_LAST_VISITED_ERROR = 'DISCUSSION_UPDATE_LAST_VISITED_ERROR';

export const DISCUSSION_BOARD_LOAD_THREADS_RESET = 'DISCUSSION_BOARD_LOAD_THREADS_RESET';
export const DISCUSSION_BOARD_LOAD_THREADS_START = 'DISCUSSION_BOARD_LOAD_THREADS_START';
export const DISCUSSION_BOARD_LOAD_THREADS_SUCCESS = 'DISCUSSION_BOARD_LOAD_THREADS_SUCCESS';
export const DISCUSSION_BOARD_LOAD_THREADS_ERROR = 'DISCUSSION_BOARD_LOAD_THREADS_ERROR';

export const DISCUSSION_THREAD_LOAD_REPLIES_START = 'DISCUSSION_THREAD_LOAD_REPLIES_START';
export const DISCUSSION_THREAD_LOAD_REPLIES_SUCCESS = 'DISCUSSION_THREAD_LOAD_REPLIES_SUCCESS';
export const DISCUSSION_THREAD_LOAD_REPLIES_ERROR = 'DISCUSSION_THREAD_LOAD_REPLIES_ERROR';

export const DISCUSSION_UPDATE_SETTINGS = 'DISCUSSION_UPDATE_SETTINGS';

export const DISCUSSION_BOARD_SORT = 'DISCUSSION_BOARD_SORT';

export const DISCUSSION_BOARD_SEARCH_CLEAR = 'DISCUSSION_BOARD_SEARCH_CLEAR';
export const DISCUSSION_BOARD_SEARCH_START = 'DISCUSSION_BOARD_SEARCH_START';
export const DISCUSSION_BOARD_SEARCH_SUCCESS = 'DISCUSSION_BOARD_SEARCH_SUCCESS';
export const DISCUSSION_BOARD_SEARCH_ERROR = 'DISCUSSION_BOARD_SEARCH_ERROR';

export const DISCUSSION_BOARD_VIEW_RETURN = 'DISCUSSION_BOARD_VIEW_RETURN';
export const DISCUSSION_BOARD_VIEW_CHANGE_THREAD_START =
  'DISCUSSION_BOARD_VIEW_CHANGE_THREAD_START';
export const DISCUSSION_BOARD_VIEW_SET_CURRENT_THREAD = 'DISCUSSION_BOARD_VIEW_SET_CURRENT_THREAD';
export const DISCUSSION_BOARD_VIEW_SET_CURRENT_POST = 'DISCUSSION_BOARD_VIEW_SET_CURRENT_POST';

export const DISCUSSION_BOARD_JUMPER_SET_JUMPER = 'DISCUSSION_BOARD_JUMPER_SET_JUMPER';
export const DISCUSSION_BOARD_JUMPER_SET_POST = 'DISCUSSION_BOARD_JUMPER_SET_POST';
export const DISCUSSION_BOARD_JUMPER_SET_USER = 'DISCUSSION_BOARD_JUMPER_SET_USER';
export const DISCUSSION_BOARD_JUMPER_SUMMARY_LOAD_START =
  'DISCUSSION_BOARD_JUMPER_SUMMARY_LOAD_START';
export const DISCUSSION_BOARD_JUMPER_SUMMARY_LOAD_SUCCESS =
  'DISCUSSION_BOARD_JUMPER_SUMMARY_LOAD_SUCCESS';
export const DISCUSSION_BOARD_JUMPER_SUMMARY_LOAD_ERROR =
  'DISCUSSION_BOARD_JUMPER_SUMMARY_LOAD_ERROR';
export const DISCUSSION_BOARD_JUMPER_LOAD_START = 'DISCUSSION_BOARD_JUMPER_LOAD_START';
export const DISCUSSION_BOARD_JUMPER_LOAD_SUCCESS = 'DISCUSSION_BOARD_JUMPER_LOAD_SUCCESS';
export const DISCUSSION_BOARD_JUMPER_LOAD_ERROR = 'DISCUSSION_BOARD_JUMPER_LOAD_ERROR';

export const DISCUSSION_BOARD_SCROLL_TO_POST_START = 'DISCUSSION_BOARD_SCROLL_TO_POST_START';
export const DISCUSSION_BOARD_SCROLL_TO_POST_SUCCESS = 'DISCUSSION_BOARD_SCROLL_TO_POST_SUCCESS';
export const DISCUSSION_BOARD_SCROLL_TO_POST_ERROR = 'DISCUSSION_BOARD_SCROLL_TO_POST_ERROR';

export const DISCUSSION_POST_SET_INITIAL_STATE = 'DISCUSSION_POST_SET_INITIAL_STATE';

export const DISCUSSION_WRITING_START = 'DISCUSSION_WRITING_START';
export const DISCUSSION_WRITING_SAVE_START = 'DISCUSSION_WRITING_SAVE_START';
export const DISCUSSION_WRITING_SAVE_SUCCESS = 'DISCUSSION_WRITING_SAVE_SUCCESS';
export const DISCUSSION_WRITING_SAVE_ERROR = 'DISCUSSION_WRITING_SAVE_ERROR';
export const DISCUSSION_WRITING_DISCARD = 'DISCUSSION_WRITING_DISCARD';
export const DISCUSSION_WRITING_KEEP_WORKING = 'DISCUSSION_WRITING_KEEP_WORKING';

export const DISCUSSION_POST_TOGGLE_BODY_EXPANSION = 'DISCUSSION_POST_TOGGLE_BODY_EXPANSION';
export const DISCUSSION_POST_BATCH_SET_BODY_EXPANSION = 'DISCUSSION_POST_BATCH_SET_BODY_EXPANSION';
export const DISCUSSION_THREAD_TOGGLE_REPLIES_EXPANSION =
  'DISCUSSION_THREAD_TOGGLE_REPLIES_EXPANSION';
export const DISCUSSION_POST_VIEWED_MANUAL_TOGGLED = 'DISCUSSION_POST_VIEWED_MANUAL_TOGGLED';
export const DISCUSSION_POST_VIEWED_AUTO_TOGGLED = 'DISCUSSION_POST_VIEWED_AUTO_TOGGLED';

export const DISCUSSION_POST_SET_NOT_NEW = 'DISCUSSION_POST_SET_NOT_NEW';

export const DISCUSSION_POST_REPORT_INAPPROPRIATE_START =
  'DISCUSSION_POST_REPORT_INAPPROPRIATE_START';
export const DISCUSSION_POST_REPORT_INAPPROPRIATE_SUCCESS =
  'DISCUSSION_POST_REPORT_INAPPROPRIATE_SUCCESS';
export const DISCUSSION_POST_REPORT_INAPPROPRIATE_FAILURE =
  'DISCUSSION_POST_REPORT_INAPPROPRIATE_FAILURE';
